### ISSUE TITLE
Multiple file compilation is not working!!

### ISSUE THREAD

**Issue by r3haan** [jlelong/LaTeX-Workshop-wiki#104]
I tried to compile multiple file project but it is not compiling it is always showing errors. Could you please help me with it?
It is always showing "Recipe terminated with error". I am attaching the screenshot below.
![Screenshot (259)](https://user-images.githubusercontent.com/120785182/208240742-79a94ff9-13f8-4704-a461-0d6b3727c130.png)

please help!!

**Comment by jlelong** [comment]
Here, we only handle issues related to the documentation of LaTeX-Workshop. For issues related to LW itself, please use https://github.com/James-Yu/LaTeX-Workshop/issues

Before opening a new issue there, please make sure your issue is not a pure LaTeX problem unrelated to LW

**Comment by r3haan** [comment]
I have worked on the same project using texmaker. .it worked there but not
in LW

**Comment by jlelong** [comment]
If you do think that there is an issue with LW, open a bug report at https://github.com/James-Yu/LaTeX-Workshop/issues and make sure to fill in all the needed information (especially the LW and LaTeX compiler logs) and provide a minimal working example to reproduce the problem.
