### ISSUE TITLE
Structure field doesn't support longer .tex files and other included .tex files

### ISSUE THREAD

**Issue by EERCrso** [jlelong/LaTeX-Workshop-wiki#107]
For longer .tex files, the structure is no longer visible. Also, the structure is not supporting the \include command: the chapters, sections, subsections, etc. in it.

![ok](https://user-images.githubusercontent.com/66819699/222450854-fc05507d-a76f-4a14-963f-46e963c33b18.png)

**Comment by jlelong** [comment]
This repo only holds the content of the wiki. If you want to report an issue against the Latex-Workshop extension, go to https://github.com/James-Yu/LaTeX-Workshop/

**Comment by EERCrso** [comment]
Of course, my mistake, thank you.
