### ISSUE TITLE
Using placeholders • and TAB

### ISSUE THREAD

**Issue by Lekain** [jlelong/LaTeX-Workshop-wiki#116]
When editing a Tex file, the role of placeholder • is erratic. When several of these are put sequentially in a snippet, the TAB only moves the pointer to the first • and behaves erratically afterwards. It is not possible to get out of an environment using • when this placeholder is outside the environment. Would it be possible to program the • so that TAB moves seamlessly from • to • ?

**Comment by jlelong** [comment]
This is the repo for the wiki of LaTeX-Workshop. If you would like to fill an issue against the extension itself, please go to https://github.com/James-Yu/LaTeX-Workshop/issues and provide a small example
