### ISSUE TITLE
Which placeholders the "latex-workshop.latex.outDir" option accepts?

### ISSUE THREAD

**Issue by ShaiAvr** [jlelong/LaTeX-Workshop-wiki#120]
In the [wiki page](https://github.com/James-Yu/LaTeX-Workshop/wiki/View#latex-workshoplatexoutdir) of the `latex-workshop.latex.outDir` options it says at the end: 

> The following placeholders defined in the [recipes section](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#placeholders) can be used.

And that's it. From this wording, it seems like not all placeholders are supported by this option, but no list of supported placeholders is provided. When I first read it, I made the dumb mistake of thinking that only the `%DIR%` placeholder is supported since this is what was written immediately after this sentence. Then I realized it was the default value of the option. I think the phrasing of this sentence needs to be changed. If all the placeholders in the [recipes section](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#placeholders) can be used, then it should be changed to something like

> All the placeholders defined in the [recipes section](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#placeholders) can be used.

If there are placeholders that can't be used with this setting, then a list of the supported ones (or the unsupported ones if it's shorter) should be provided.

**Comment by jlelong** [comment]
Close by b5a723b
