### ISSUE TITLE
Document configuration variables

### ISSUE THREAD

**Issue by jlelong** [jlelong/LaTeX-Workshop-wiki#44]
Some configuration variables from `package.json` are not documented in the wiki

- [x] `latex-workshop.chktex.delay`
- [x] `latex-workshop.chktex.run`
- [x] `latex-workshop.docker.image.latex`
- [x] `latex-workshop.hover.ref.number.enabled`
- [x] `latex-workshop.intellisense.update.aggressive.enabled`
- [x] `latex-workshop.intellisense.update.delay`
- [x] `latex-workshop.latex.external.build.args`
- [x] `latex-workshop.latex.rootFile.useSubFile`
- [x] `latex-workshop.message.convertFilenameEncoding`
- [x] `latex-workshop.progress.barLength`
- [x] `latex-workshop.progress.barStyle`
- [x] `latex-workshop.progress.runIconType`
- [x] `latex-workshop.texdoc.args`
- [x] `latex-workshop.view.pdf.external.synctex.args`
- [x] `latex-workshop.view.pdf.external.synctex.command`
- [x] `latex-workshop.viewer.pdf.internal.port`

On the contrary, some variables documented in the wiki do not exist anymore

- [x] `latex-workshop.chktex.interval`
- [x] `latex-workshop.hover.ref.numberAtLastCompilation.enabled`
- [x] `latex-workshop.latex.texdoc.args`
- [x] `latex-workshop.latex.texdoc.path`
- [x] `latex-workshop.view.pdf.external.command`
- [x] `latex-workshop.view.pdf.external.synctex`

**Comment by trevorgunn** [comment]
You should be able to cross off `latex-workshop.view.pdf.external.command` and `latex-workshop.view.pdf.external.args` from the "do not exist" section now.

**Comment by tamuratak** [comment]
Sorry. I unintentionally edited the first post. I have reverted it.

**Comment by jlelong** [comment]
@tamuratak  No worries.
