### ISSUE TITLE
Some commands / variables are not documented

### ISSUE THREAD

**Issue by jlelong** [jlelong/LaTeX-Workshop-wiki#56]
#### Configuration variables

- [x] `latex-workshop.intellisense.preview.enabled`
- [x] `latex-workshop.progress.location`
- [x] `latex-workshop.view.pdf.tab.backgroundColor`

#### Commands

- [x] `latex-workshop.actions`
- [x] `latex-workshop.addtexroot`
- [ ] ~~`latex-workshop.citation`~~
- [x] `latex-workshop.clean`
- [x] `latex-workshop.kill`
- [ ] ~~`latex-workshop.log`~~
- [x] `latex-workshop.refresh-viewer`
- [x] `latex-workshop.saveWithoutBuilding`
- [ ] ~~`latex-workshop.showCompilationPanel`~~
- [x] `latex-workshop.showSnippetPanel`
- [ ] ~~`latex-workshop.synctex`~~
- [ ] ~~`latex-workshop.tab`~~
- [x] `latex-workshop.texdoc`
- [x] `latex-workshop.texdocUsepackages`
- [x] `latex-workshop.view`

**Comment by trevorgunn** [comment]
I will add documentation for `latex-workshop.progress.location` since I wrote that feature. Then I will try to help document some of the other commands.

I don't think we need to document `latex-workshop-dev.*` (at least not in the Wiki). Those commands aren't intended for users to use.

**Comment by jlelong** [comment]
Right for `latex-workshop-dev.*`.

**Comment by trevorgunn** [comment]
`latex-structure.toggle-follow-cursor` seems to be an internal function that you used to fix James-Yu/LaTeX-Workshop#1156; I don't think it requires documentation.

**Comment by jlelong** [comment]
You are right and some other commands may also not required documentation.
