### ISSUE TITLE
Incompatibility with "Path Intellisense"

### ISSUE THREAD

**Issue by Vinno97** [jlelong/LaTeX-Workshop-wiki#79]
Just as with [Path Autocomplete](https://marketplace.visualstudio.com/items?itemName=ionutvmi.path-autocomplete), the [Path Intellisense](https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense) extension breaks the autocompletion for bibliograpy citations. 

I have added this incompatibility in a PR: #78

**Comment by jlelong** [comment]
Merging #78
