### ISSUE TITLE
Broken link for SumatraPDF discussion

### ISSUE THREAD

**Issue by Yarakashi-Kikohshi** [jlelong/LaTeX-Workshop-wiki#94]
The reference link on the following page as “see here” is broken.

> https://github.com/James-Yu/LaTeX-Workshop/wiki/View#sumatrapdf

This is because the discussion forum has moved.

## Wrong link

```
https://forum.sumatrapdfreader.org/t/inverse-search-not-performed-for-vs-code-exe/4486/20
```

https://forum.sumatrapdfreader.org/t/inverse-search-not-performed-for-vs-code-exe/4486/20

Go to “Not Found” page...

## Correct link

```
https://forum.sumatrapdfreader.org/t/inverse-search-not-performed-for-vs-code-exe/4486
```

https://forum.sumatrapdfreader.org/t/inverse-search-not-performed-for-vs-code-exe/4486

However, it is difficult to see which part of the link page is being referred to. You can also make the reference point clearer by adding highlights to specific characters. See https://developer.chrome.com/blog/new-in-chrome-80/#more

```
https://forum.sumatrapdfreader.org/t/inverse-search-not-performed-for-vs-code-exe/4486/#:~:text=DigNative
```

https://forum.sumatrapdfreader.org/t/inverse-search-not-performed-for-vs-code-exe/4486/#:~:text=DigNative

----------

The Sumatra Reader Discussion Forum moved to [GitHub Discussion][sumatrapdf-github-dis] of SumatraPDF.

[sumatrapdf-github-dis]: https://github.com/sumatrapdfreader/sumatrapdf/discussions

This past discussion logs will be archived. See https://github.com/sumatrapdfreader/sumatrapdf/discussions/2293

**Comment by jlelong** [comment]
Would you mind making a PR to fix those links? Thanks

**Comment by Yarakashi-Kikohshi** [comment]
OK. I have never make PR before, so it may take me a little longer, but I will do it as soon as possible.
